### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by arnuschky** [slashdotdash/node-ledger-web#5]
Under which license has this been published?

**Comment by arnuschky** [comment]
Ah, found it in `package.js`.  Could you confirm that the license is MIT?

**Comment by slashdotdash** [comment]
License is MIT.

**Comment by singpolyma** [comment]
Please add a COPYING or LICENSE or License.txt file so that the whole license text is included and not just the name of it hidden in a metadata file :)
